'spurious-sqs':
  :image: 'spurious/sqs'
  :hostname: 'sqs.spurious.localhost'

'spurious-s3':
  :image: 'spurious/s3'
  :hostname: 's3.spurious.localhost'

'spurious-dynamo':
  :image: 'spurious/dynamodb'
  :hostname: 'dynamodb.spurious.localhost'

'spurious-memcached':
  :image: 'smaj/memcached'

'spurious-elasticache':
  :image: 'spurious/elasticache'
  :link:
    - 'spurious-memcached:memcached01'
  :env:
    FAKEELASTICACHE_DEFAULT_HOST: '127.0.0.1'

'spurious-elasticache-docker':
  :image: 'spurious/elasticache'
  :ignore:
    :create: true
    :delete: true
  :link:
    - 'spurious-memcached:memcached01'

'spurious-browser':
  :image: 'spurious/browser'
  :link:
    - 'spurious-dynamo:dynamodb.spurious.localhost'
    - 'spurious-sqs:sqs.spurious.localhost'
    - 'spurious-s3:s3.spurious.localhost'
  :hostname: 'browser.spurious.localhost'
